### ISSUE TITLE
roles management

### ISSUE THREAD

**Issue by KudMath** [rmuif/cli#25]
Hi, After using `yarn roles admin,premium` and having it run apparently successfuly, my user still has no roles :/ Help plz?

**Comment by KudMath** [comment]
I should add that my `idTokenResult` in the `getRoles` function indeed has no roles listed in claims

**Comment by phoqe** [comment]
You are using the command incorrectly, try reading https://docs.rmuif.com/authorization#setting-a-users-roles.

**Comment by phoqe** [comment]
Closing, if this issue persists, reopen. Thank you.

**Comment by KudMath** [comment]
Oops sorry. I was indeed. Thanks for the answer.
